language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: n3cENh5gzoUL1oVRawfU7t4hpd5eNFYa97GwDRA+J9MsR5wPII5oFHtd0pu8TFL1hWemBblBf6AjPYyKK1A26ZAJo4lLDRzUV7hR7EETSfI92nIsoMefVJ0cQ9e5Fgv/rGNiSnAatHTO6M5gURI/9q7Ef2pFum3/M2XEFPdjbFU8+IZ4IRynRIagorg35xfpom6K9MPkOlph4VidAVjZMnU+zpFxImwvOrNGQzYaoFzrKE91tZ/8xa8DjVV32vZ/3zxCXJY/uOtc+BImUEwrN8fRBycetnm+Xy3JDJsoCdqFisFgZhtnHQ3DTLH8A/L5BEbwd15PO6Dtv4rn7uVe4B+DdEyjn5b7TFrUGFfG0ehky7cbaaU8zSQTxrQuJ1RZOs0Doi/Mk3RJxaZY15G7146J+xHIgNfQYFogkPhwUpsx7M7ivBQpbGs0/fBoH+h21j3WPwGRJX4vIpBANozo1EnHP3BoPoHwCMW/AeV2PA4tGzs+LauLT8g518sywRSwLcVj2mjGj1W7s80bPHgUGVvstnnILzV5cxOCT6v0zZ0C9cpNheo8ed1WWd4Geh6r4lFKw5zSWNB8JmRDcDozgMJWbEVBF9+plpOvL41IBJtaO610LfYT9XDej071VAUNQNFMX+6m/Fu8mhjQeDoBb8BG71Kc5xjOtyQTYkTbXbU=
  app: istic-notificaciones
