language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: KABLmG69nRw+1lIufaVsNscAUJ6+mIrF4kN0IxYX79Ad3blT8BBDjXD0i7oZEQlSGdBPsH8svvM1+emW+kUFe4lDojGYYQ3aMtZQhuMqVRBo3C93OUkJ9/qRQXHoqjuKkQWaNbfjZb131wDfVe/NfnkBZ81heAMX4QNSZeUomgLmxzWhIf5twrt2VtclSBtr4buyqTUKaox9Nfe5svjA9NWz/dkk3j6hQwYBP7gWlb0EsOfr06s52TlhHdrHlMkTN6nFlgbtFZAXwsU3fUPGIQel4sW1hk7Mi8cg1gyEPn6kgZt3MDAoVZNzxD2Fpqxl1B/ataOGMm5xSF16sNl0Z/LQyapLi+2nt+eTos1Nn5BBy8cX4YHwT/dzA4ZyirrUJZeJzMrnGnRRDy65kKbfPo8q/lUcZ2hJHTLUlndRWQc3561CYoXFZQJVZpX+ecVIWabKpL+JEeGHpN/v/gE+e56SCD0fjJoBfOwrOnhavBcA7DAy0+O9+9/S8/WTY++ZCOyCabvzJDvzCtKx9PCxt2ypAnSlxwLRwp6ZCq2KANLjZbc8qXIYJs98yLIQH1xAMiNRlKJ1Z3clTcyOC0v6HXwah8F+jmaNngGNOJQYqcOzw/onWG96cTJfRHkhWD1bzPdfm3QOjHPge0Z1ZJ7u1hIZ6CPFZC3XB9Njyh3/2pE=
  app: istic-notificaciones
