language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: C/G4q4RwhjE4tfu0NdTjzkaCpkM37tkWMCgS8EGtfZMRcH+KEWOhoBAXFjjO9aqXVdhE9GWG5x7Uk995IJCVYKCGUUGtN4uiFrfXryDc8AQXBHTUGc1q2v4gbhME56RqULQOJBF7NIa3rWqU7mv//OmFnAYDbbVGNPuh5T5+qyYaIckh8PW9x7TvC4x6fzMCV3KmMXNyxDXJ8S0yOt0k193XnZU2NMSh9EBLvCTyrG29iVOVHpy2VSqzDGqzEI56SVeYnK4Za8gkMK8JeKwzlAQyfjGePD2efNz087h3/5pMOVQqPFUIStEgMmo5KNxJ+71Go8uDuU99BRKFsVJOx+u0kq/s+Uj6LmI0UHMF/NeOZBzRjH1bwVze4wlZgi5KQaaVQMnkuy8OyF8CqmOm7aIofhS4wjcNBapMFoJOO449b2Faaiq6byT4sQKkKA/13QpSP2OGRotp95pXQMme/Uk7tkHf2+Zb0PqwPBUyTNSqNXlh8/lAC1v0PpDO3RKm88a+ZjHWOa7A8ylcuXIqAWyQebGPEWQ1t3X98IL4hZqVizZlQC74IRUqSn6u8w4WAWjGuJsjTneRfBnx5z+AXJFZI0SN2T/WnqGW5oJmMSHnwgZrcw4y9HDBE0Z4Ukt+vISZvTcvs+c2zsVDP3BYY7XU5P1tclh55BGeD7QwHF0=
  app: istic-notificaciones
